### ISSUE TITLE
Always rely on a default setting

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/monetdb-pystethoscope#18]
poetry run stethoscope.py -F json
poetry run stethoscope.py -F json sf10
poetry run pystethoscope -t identity -F json sf10

Only the last one makes a proper connection.
The former 2 trigger errors:
Using python3 (3.7.7)

[OSError]
[Errno 13] Permission denied

**Comment by kutsurak** [comment]
The database to connect to is a required argument so it needs to be given. 

For the optional arguments this was fixed.
