### ISSUE TITLE
README documentation

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/monetdb-pystethoscope#23]
Clearly separate the use from development by the addition of the simple example.
Warn for possible --upgrade and --user issues

**Comment by kutsurak** [comment]
There is a section called "Installation" and a different one "Installation for development" in the README. I am not sure how I can separate these more clearly.

About the `--upgrade` or `--user` issues the common assumption in python projects is that users know how to use pip, or will look up its documentation. Some examples:

https://github.com/gijzelaerr/pymonetdb
https://docs.sqlalchemy.org/en/14/intro.html#installation
https://github.com/pallets/flask#installing
https://docs.djangoproject.com/en/3.2/topics/install/#installing-official-release
https://github.com/dbcli/pgcli

Moreover both the README and the documentation explicitly recommend the use of virtual environments and point to documentation about their use (https://realpython.com/python-virtual-environments-a-primer/).
